import { Subject } from '@/types/Subject';

export const subjects: Subject[] = [
    { id: 'travail-eleves', name: 'Travail des élèves', premium: false, image: 'https://firebasestorage.googleapis.com/v0/b/recapeps-platform.firebasestorage.app/o/snapshots_subject%2FContexte-politique.svg?alt=media&token=4b99cf39-28c0-4296-8c74-ff0f7e750e1c', link: "https://drive.google.com/file/d/1pLgwHlgQXoaCBfCOmoPTOUOxb36nbS8r/view?usp=sharing" },
    { id: 'les-techniques', name: 'Les techniques', premium: false, image: "https://firebasestorage.googleapis.com/v0/b/recapeps-platform.firebasestorage.app/o/snapshots_subject%2Ftechnique.svg?alt=media&token=9bb564b2-d4ba-4887-92ef-1bf1cc66ee81", link: "https://drive.google.com/file/d/1KSfL6gjS7ExSCDrhsPoa3ospZGMQFtaa/view?usp=sharing" },
    { id: 'sport-scolaire', name: 'Sport scolaire', image: 'https://firebasestorage.googleapis.com/v0/b/recapeps-platform.firebasestorage.app/o/snapshots_subject%2FSport%20scolaire.svg?alt=media&token=d92adbe9-8109-4451-84fc-aaf2cf39d7f8', premium: false, link: "https://drive.google.com/file/d/1of_98lO5G59KDc6MP3Ls64O3obQF8n0z/view?usp=sharing" },
    { id: 'sciences', name: 'Sciences', image: 'https://firebasestorage.googleapis.com/v0/b/recapeps-platform.firebasestorage.app/o/snapshots_subject%2Fsciences.svg?alt=media&token=41b5a8cd-a4db-4b11-b192-4e93c978a4a9', premium: false, link: "https://drive.google.com/file/d/1gr0rY4cs3ZtSsGAK4fPKAcO9XJLn3lkv/view?usp=sharing" },
    { id: 'sante', name: 'Santé', image: 'https://firebasestorage.googleapis.com/v0/b/recapeps-platform.firebasestorage.app/o/snapshots_subject%2FSante.svg?alt=media&token=e7419dd1-65b8-422c-b477-629714deb6ab', premium: false, link: "https://drive.google.com/file/d/1ifV7ZJY53k6CMuxc7mSX3r1k931ovbhd/view?usp=sharing" },
    { id: 'nature-citoyennete', name: 'Nature et citoyenneté', image: 'https://firebasestorage.googleapis.com/v0/b/recapeps-platform.firebasestorage.app/o/snapshots_subject%2Fnature.svg?alt=media&token=7c290552-2371-4a54-8718-1dd1962d40c2', premium: false, link: "https://drive.google.com/file/d/1Vq4_UkecVoouq4DjTC_3WvjyR4qElp5d/view?usp=sharing" },
    { id: 'mixite-sexuee', name: 'La mixité sexuée', image: 'https://firebasestorage.googleapis.com/v0/b/recapeps-platform.firebasestorage.app/o/snapshots_subject%2Fmixite_sexuee.svg?alt=media&token=83274934-11a5-4943-8e20-94486f4bc6e4', premium: true, link: "https://drive.google.com/file/d/1GVdFbA6owhv3UpJi_Jdcxrl80vKHLRBO/view?usp=sharing" },
    { id: 'evaluation', name: 'Evaluation', premium: true, image: 'https://firebasestorage.googleapis.com/v0/b/recapeps-platform.firebasestorage.app/o/snapshots_subject%2Fevaluation.svg?alt=media&token=aa561fa1-52ba-4873-a363-46f33f19e9b5', link: "https://drive.google.com/file/d/1Ctr9UWyiv2ejIO7yNZAxzhvFpnfc6ZLN/view?usp=sharing" },
    { id: 'culture-corporelle', name: 'Culture corporelle', premium: true, image: 'https://firebasestorage.googleapis.com/v0/b/recapeps-platform.firebasestorage.app/o/snapshots_subject%2Fculture-corporelle.svg?alt=media&token=83a26cb7-9c97-4e1b-8a22-075a4d69f117', link: "https://drive.google.com/file/d/1rJ9wlM05sEMQwg79beTZWcjJFdLMs0BJ/view?usp=sharing" },
];